// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrPizza.Domain.Infra.Contexts;

namespace MrPizza.Domain.Infra.Migrations
{
    [DbContext(typeof(MrPizzaContext))]
    [Migration("20200815192955_v3")]
    partial class v3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MrPizza.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnName("endereco")
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id")
                        .HasName("PK_enderecoId");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraPedido")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdEndereco")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_pedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pizza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id")
                        .HasName("PK_pizzaId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.PizzaSabor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPizza")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSabor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_pizzaSaborId");

                    b.HasIndex("IdPizza");

                    b.HasIndex("IdSabor");

                    b.ToTable("PizzaSabor");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Sabor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id")
                        .HasName("PK_saborId");

                    b.ToTable("Sabor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62aeb419-4f3a-4e20-8a2a-dacc930d229b"),
                            Descricao = "3 Queijos",
                            Valor = 50m
                        },
                        new
                        {
                            Id = new Guid("837d08ee-32a6-48bf-9c75-ac0da4ceacde"),
                            Descricao = "Frango com requeijão ",
                            Valor = 59.99m
                        },
                        new
                        {
                            Id = new Guid("6a1d2b99-58d3-4397-9a18-2e3a2dca37d6"),
                            Descricao = "Mussarela ",
                            Valor = 42.5m
                        },
                        new
                        {
                            Id = new Guid("f11009b9-a501-4469-b72a-ba88b1c8e264"),
                            Descricao = "Calabresa ",
                            Valor = 42.5m
                        },
                        new
                        {
                            Id = new Guid("89af4cc9-dcf4-431c-9943-998f056cacf4"),
                            Descricao = "Pepperoni",
                            Valor = 55m
                        },
                        new
                        {
                            Id = new Guid("19bce1a6-4830-4d9d-b24c-6aaa7be83f85"),
                            Descricao = "Portuguesa ",
                            Valor = 45m
                        },
                        new
                        {
                            Id = new Guid("3231493d-51be-4b95-b94d-de454b2d1d63"),
                            Descricao = "Veggie ",
                            Valor = 59.99m
                        });
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("EmailLogin")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.HasKey("Id")
                        .HasName("PK_usuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("IdUsuario");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Usuario", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pizza", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Pizzas")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.PizzaSabor", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Pizza", "Pizza")
                        .WithMany("PizzaSabores")
                        .HasForeignKey("IdPizza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MrPizza.Domain.Entities.Sabor", "Sabor")
                        .WithMany("PizzaSabores")
                        .HasForeignKey("IdSabor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
