// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrPizza.Domain.Infra.Contexts;

namespace MrPizza.Domain.Infra.Migrations
{
    [DbContext(typeof(MrPizzaContext))]
    [Migration("20200815192818_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MrPizza.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnName("endereco")
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id")
                        .HasName("PK_enderecoId");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraPedido")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdEndereco")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_pedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pizza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id")
                        .HasName("PK_pizzaId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.PizzaSabor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPizza")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSabor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_pizzaSaborId");

                    b.HasIndex("IdPizza");

                    b.HasIndex("IdSabor");

                    b.ToTable("PizzaSabor");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Sabor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id")
                        .HasName("PK_saborId");

                    b.ToTable("Sabor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8be7a499-3804-4d03-8012-5da4f3c6fdee"),
                            Descricao = "3 Queijos",
                            Valor = 50m
                        },
                        new
                        {
                            Id = new Guid("2fa0b740-14e0-4835-a4a1-192b085bbc8b"),
                            Descricao = "Frango com requeijão ",
                            Valor = 59.99m
                        },
                        new
                        {
                            Id = new Guid("d128e8c5-fbae-4f08-971a-3f665b4cc535"),
                            Descricao = "Mussarela ",
                            Valor = 42.5m
                        },
                        new
                        {
                            Id = new Guid("b16693c9-ec4b-470a-a27d-2fe17662d555"),
                            Descricao = "Calabresa ",
                            Valor = 42.5m
                        },
                        new
                        {
                            Id = new Guid("a568bf5f-3761-4825-9d5c-f337f337755c"),
                            Descricao = "Pepperoni",
                            Valor = 55m
                        },
                        new
                        {
                            Id = new Guid("b13926e4-0205-4c48-bc71-3c2e7a08d203"),
                            Descricao = "Portuguesa ",
                            Valor = 45m
                        },
                        new
                        {
                            Id = new Guid("d4e50a26-c51d-4479-bc24-890645106050"),
                            Descricao = "Veggie ",
                            Valor = 59.99m
                        });
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("EmailLogin")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("IdEndereco")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.HasKey("Id")
                        .HasName("PK_usuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("IdUsuario");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Usuario", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pizza", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Pizzas")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.PizzaSabor", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Pizza", "Pizza")
                        .WithMany("PizzaSabores")
                        .HasForeignKey("IdPizza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MrPizza.Domain.Entities.Sabor", "Sabor")
                        .WithMany("PizzaSabores")
                        .HasForeignKey("IdSabor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
