// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrPizza.Domain.Infra.Contexts;

namespace MrPizza.Domain.Infra.Migrations
{
    [DbContext(typeof(MrPizzaContext))]
    [Migration("20200815193126_v4")]
    partial class v4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MrPizza.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnName("endereco")
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id")
                        .HasName("PK_enderecoId");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraPedido")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdEndereco")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_pedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pizza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id")
                        .HasName("PK_pizzaId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.PizzaSabor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPizza")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSabor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_pizzaSaborId");

                    b.HasIndex("IdPizza");

                    b.HasIndex("IdSabor");

                    b.ToTable("PizzaSabor");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Sabor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id")
                        .HasName("PK_saborId");

                    b.ToTable("Sabor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd332ae9-affe-4f19-841e-c13cc45d6b30"),
                            Descricao = "3 Queijos",
                            Valor = 50m
                        },
                        new
                        {
                            Id = new Guid("97778198-5c3d-419c-844c-824991622c5f"),
                            Descricao = "Frango com requeijão ",
                            Valor = 59.99m
                        },
                        new
                        {
                            Id = new Guid("ea15ccfc-9fbe-41e6-874e-9a9ae6412cba"),
                            Descricao = "Mussarela ",
                            Valor = 42.5m
                        },
                        new
                        {
                            Id = new Guid("e6b5473e-3e91-4676-8840-f5bc95c58f95"),
                            Descricao = "Calabresa ",
                            Valor = 42.5m
                        },
                        new
                        {
                            Id = new Guid("f5b177f0-b823-430a-bc76-6150dbd2f6bb"),
                            Descricao = "Pepperoni",
                            Valor = 55m
                        },
                        new
                        {
                            Id = new Guid("f51d2342-79dd-4817-b637-1db10bc95b0a"),
                            Descricao = "Portuguesa ",
                            Valor = 45m
                        },
                        new
                        {
                            Id = new Guid("2915805c-dd98-4e97-b212-ee0132e6512f"),
                            Descricao = "Veggie ",
                            Valor = 59.99m
                        });
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("EmailLogin")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.HasKey("Id")
                        .HasName("PK_usuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("IdUsuario");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Usuario", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.Pizza", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Pizzas")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("MrPizza.Domain.Entities.PizzaSabor", b =>
                {
                    b.HasOne("MrPizza.Domain.Entities.Pizza", "Pizza")
                        .WithMany("PizzaSabores")
                        .HasForeignKey("IdPizza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MrPizza.Domain.Entities.Sabor", "Sabor")
                        .WithMany("PizzaSabores")
                        .HasForeignKey("IdSabor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
